### ISSUE TITLE
Is this still working as of today?

### ISSUE THREAD

**Issue by ghost** [morris/typekit-cache#13]
I successfully used it for the past months and everything was working.
The class `wf-cached` was correctly added to the html element.
Two days ago I setup a new website and it wasn't working anymore. I also tried to clean up the cookies for the previous website (where everything was working) and it stopped working as well.
I now got back that terrible behavior of the FOUC.

PS: Yes I also tried to create a new Typekit kit.

**Comment by morris** [comment]
🔥  http://blog.typekit.com/2016/07/28/changes-to-web-font-serving-on-typekit/

Looks like typekit-cache needs a complete overhaul to work with the new method, not even sure if it will work at all with an inline stylesheet containing URLs.

In any case, can you confirm that nothing actually _breaks_? It's just the FOUC that's back, right?

**Comment by ghost** [comment]
Yes, it's just the FOUC that's back. So right now there's no reason to use this version of the script, correct?

**Comment by ghost** [comment]
I didn't understand if with the new update we should use the default embed code (non-async) or we should use the advanced embed code (async) -- the one that we were using before.

**Comment by morris** [comment]
Yep, looks that way. The Typekit update does not require you to make any changes, it just works differently and makes typekit-cache defunct for now.

**Comment by ghost** [comment]
Incredible that after many years of Typekit and in general webfonts, we still don't have a solution to the awful FUOC problem that affects our websites. typekit-cache was amazing for this. I hope we'll be able to find a workaround to make it work and shine again.

**Comment by garyrowswell** [comment]
Below is a TypeKit Cache alternative I've written to avoid FOUT in Chrome, any opinions?

if (Modernizr.history) {

```
cached = localStorage['tkc'];

if (cached) {

    $('head').append($('<style/>',{'text':cached}));

}

$('head').on('DOMNodeInserted',function(e) {

    if (e.target.tagName == 'STYLE' && e.target.textContent.indexOf('https://fonts.typekit.net/') > -1) {

        if (cached != e.target.textContent) {

            localStorage['tkc'] = e.target.textContent;

        }

    }

});
```

}

**Comment by morris** [comment]
Yeah that's an option, however since the cached CSS holds URLs itself (which are cached for 1y according to the Typekit blog entry) I'm unsure if it's worth it because the FOUC is still possible, right? Before the update, the cache would hold complete fonts (base64) and therefore the FOUC was impossible. Definitely something to investigate further.

**Comment by garyrowswell** [comment]
The font files that the CSS points to are cached in the browser so they load instantly. FOUC should only happen when/if the cached font files expire or are removed.

Hopefully the expiry on the cached font files roll forward with each page load, and then you'd only get FOUC if you were returning to the site after a year of absence, but even if they don't you'd still get a year FOUC free as far as I can see.

**Comment by morris** [comment]
Just implemented an update which caches the CSS at least. I'm still seeing a micro-FOUT - unsure if it's unavoidable. Also, fonts are gone after a regular refresh if you're offline :( the update is still beta and needs tweaking (e.g. infinite checks for new fonts).

@garyrowswell @invulsion would you mind checking if it's any good?

**Comment by morris** [comment]
Any open issues with the current revision? Otherwise I'll just remove the Beta tag
