### ISSUE TITLE
Recursive call `cache` function

### ISSUE THREAD

**Issue by OleksandrPopov-San4o** [morris/typekit-cache#17]
Is there any reason of calling cache recursively in set timeout? 
Also there is ` if ( storage[ key ] )  ` but anyway cache is calling

**Comment by morris** [comment]
Two reasons (or, actually, design decisions):

1. typekit-cache makes very few assumptions about the implementation of Typekit's font loader. Repeated polling for matching CSS ensures that fonts will be cached at some point, regardless of *how* and *when* they are loaded. With exponential backoff this is fairly performant.
2. It's hard for typekit-cache to know if a Typekit was modified, or multiple Typekits are used on the same domain, so the only viable option is to rewrite the cache on every page load.
