### ISSUE TITLE
An issue with Windows Phone and older devices

### ISSUE THREAD

**Issue by artemgordinskiy** [morris/typekit-cache#2]
For a long time, we have been observing lots of strange requests that usually looked like this:

```
https://ourdomain.com/f/Cf18XFAS[...].woff?3bb2a6e53c9684ffdc9a98f5[...]
https://ourdomain.com/f/9vhG4QCD[...].otf?3bb2a6e53c9[...]
```

Most of these were coming from Windows Phone devices, but there also were some really old Android and iOS devices. After much debugging, we have found these requests to be made by the browser, when trying to download the fonts from the font-face declaration in Typekit's stylesheets, that were embedded into the page by this script. This was weird, because Typekit always had base64-encoded fonts in their stylesheets. When, however, we changed the useragent to Windows Phone, Typekit returned stylesheets with links to the resources instead, so that font-face declaration looked like this:

``` css
@font-face {
    font-family: "alwyn-new-web";
    src: url(/f/LxfQHh_wQ[...].woff2?3bb2a6e53c968[...]) format("woff2") [..]
}
```

So when this script was inlined into the page, the browsers were trying to load the fonts from our domain, which resulted in the requests I have shown at the start.

I guess the caching script must parse the css and ensure that it contains only base64 resources, and no relative urls before inlining it?

**Comment by morris** [comment]
Thanks for reporting this. I see two immediate solutions:
1. Disable caching if relative URLs are found in the TypeKit.
2. Make relative URLs absolute using the TypeKit domain. In this case, only the CSS file is cached, not the font data.

I think I'll go for number 2 because _some_ caching is probably better than _no_ caching. This might need some testing though.

**Comment by artemgordinskiy** [comment]
I think the second option is indeed a better one. Would gladly help with testing :+1:

**Comment by morris** [comment]
Let me know if it works out :-)

**Comment by artemgordinskiy** [comment]
Seems to work well, with one slight tweak – when you pass a string literal to the `replace()` method, it replaces only the first occurrence. To replace all of them, you can use the following regex:

```
/url\(\//g
```

**Comment by morris** [comment]
Of course - thanks again!

**Comment by artemgordinskiy** [comment]
Great, thanks for working this out so fast!
