### ISSUE TITLE
Still an issue with touching window.localStorage

### ISSUE THREAD

**Issue by mikebaldry** [morris/typekit-cache#4]
any touch of `window.localStorage` needs to catch SecurityError - if you try disabling all cookies in chrome, you'll see this is raised just by calling `window.localStorage`

`Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

So, just passing `localStorage` in will cause this to fail.

**Comment by mikebaldry** [comment]
I'm seeing this as a problem with chrome when third party cookies are disabled, as my site is embedded as an iframe in other sites.

**Comment by morris** [comment]
Hmm. Wrapping everything in a try/catch-Block would be a solution. I wonder if there's a better way though. Good catch, thanks!

As a sidenote, Chrome does a bad job :-1: shouldn't it just leave localStorage as undefined if it is unavailable? That's how you check for features in most browsers nowadays. if ( window.requestAnimationFrame ) ... etc.

**Comment by mikebaldry** [comment]
I'd have thought the same. Its rather annoying!

On Fri, Feb 5, 2016 at 2:56 PM, Morris Brodersen notifications@github.com
wrote:

> Hmm. Wrapping everything in a try/catch-Block would be a solution. I
> wonder if there's a better way though. Good catch, thanks!
> 
> As a sidenote, Chrome does a bad job [image: :-1:] shouldn't it just
> leave localStorage as undefined if it is unavailable? That's how you check
> for features in most browsers nowadays. if ( window.requestAnimationFrame )
> ... etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/morris/typekit-cache/issues/4#issuecomment-180389026.

## 

Michael

www.brightbits.co.uk

Company number: 08133555
Registered in England
Registered office: 22 Finwell Road, Rainham, Kent, ME8 7PY

**Comment by morris** [comment]
https://code.google.com/p/chromium/issues/detail?id=426206

**Comment by morris** [comment]
Thanks again!
