### ISSUE TITLE
old Internet Explorer versions (i.e. IE9) use fallback fonts when using this script

### ISSUE THREAD

**Issue by janpersoons** [morris/typekit-cache#5]
can we use some sort of check when old IE versions are being used so the Typekit fonts still load?

**Comment by morris** [comment]
Can't reproduce this in IE9, tests are running fine (checked with BrowserStack). Can you provide a link to the page where it's not working?

IE8 does fail the test, and since [Typekit supports IE8](http://help.typekit.com/customer/portal/articles/6786-Browser-and-OS-support) I'll have to investigate. Thanks for reporting!

**Comment by morris** [comment]
Seems like http://stackoverflow.com/questions/20400026/htmldocument-is-undefined-in-ie8 is related - typekit-cache uses "Element", so maybe your site is in quirks mode?

**Comment by janpersoons** [comment]
It's still a local site so I can't give you a link (yet). I also test it with Browserstack and the font fails to load on IE9 on XP. I took some screenshots of IE9 and IE10. The font in the header is not rendered correctly on IE9, IE10 it is fine

![bs_win7_ie_9 0](https://cloud.githubusercontent.com/assets/1147548/13136531/b0ba77c2-d61a-11e5-8ad1-9a791b092c84.jpg)
![bs_win7_ie_10 0 1](https://cloud.githubusercontent.com/assets/1147548/13136530/b0b1bee8-d61a-11e5-89bb-2fc411a3d521.jpg)

**Comment by morris** [comment]
quick question... does it work _without_ typekit-cache? Edit: My BrowserStack does not offer XP + IE9

**Comment by janpersoons** [comment]
yes

**Comment by morris** [comment]
in the first screenshot, if you open the script tab and the console tab and refresh, is there any error?

**Comment by morris** [comment]
also try the tests: https://rawgit.com/morris/typekit-cache/master/test/index.html in your environment and check if there's any errors in the console

**Comment by janpersoons** [comment]
No errors. Also tried your link, it passed. Am I doing something wrong? This is very weird
![source](https://cloud.githubusercontent.com/assets/1147548/13169163/bace33ec-d6e3-11e5-995f-3bf125bcd018.jpg)

**Comment by morris** [comment]
typekit-cache currenlty only supports the advanced Typekit embed code which looks something like

```
<script>
  (function(d) {
    var config = {
      kitId: 'kitId',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>
```

Maybe that solves it for you. However, it seems typekit-cache is currently messing up the wf-\* classes; are you using a .wf-active check to apply web fonts? That might be the problem as well. Need to fix that asap.

**Comment by morris** [comment]
wf-active is fixed. Can you check if that did the trick? Remember to use the advanced embed code

**Comment by janpersoons** [comment]
it didn't do the trick, sorry.
When I copied the non-minified script and logged some variables, it did work. This is super weird because when I removed the console.log lines it didn't work again. The variables I logged where name, url, xhr and css right before setAttribute = proto.setAttribute. It doesn't make any sense I know.

Anyway, when I digged deeper I noticed the xhr.onreadystatechange function isn't triggered on IE9, don't know why but maybe that will help to debug

**Comment by morris** [comment]
If you can host a test page (just a reproduction of the issue) anywhere i could debug, however i cant reproduce xp+ie9. Send the link to mb@morrisbrodersen.de and i'll see what i can do.

**Comment by morris** [comment]
This should be fixed with revision 5, let me know if it works out.

**Comment by janpersoons** [comment]
yes, it works!
thanks!
