### ISSUE TITLE
Session storage

### ISSUE THREAD

**Issue by trkoch** [morris/typekit-cache#7]
Have you thought about adding the font to the session storage instead of the local storage? This should still avoid FOUT when navigating within page, but avoid filling up the storage and hitting the quota (of course, assuming many sites use typekit-cache).

**Comment by trkoch** [comment]
Thinking about it, the risk of hitting a quota should be the same, since the limit is per domain (origin). Still I like the idea that users can clear the font cache simply by closing the browser.

**Comment by morris** [comment]
I think this can be easily done by the user right now - it's just one `localStorage` reference to replace, and they're copying the snippet anyway. We could add a note to the readme saying that it's possible, though.

**Comment by trkoch** [comment]
:+1:

Adding a note the README would make users more aware of the options (`localStorage` vs. `sessionStorage`) and possible issues with the default choice (persistent cache entry for each site).

I switched to `sessionStorage` and so far it works well. The initial delay when revisiting a page (fresh cache) is negligible. For me, avoiding FOUT between page loads within one session (e.g. browsing from page A to page B on the same site) is much more important. `sessionStorage` is sufficient for this. Plus it may also avoid possible legal objections.

**Comment by morris** [comment]
So the question is, which one should be the default? I'm currently leaning towards localStorage because using it means less FOUTs. (In any case, we should add a note.)

**Comment by trkoch** [comment]
Personally I'm leaning towards `sessionStorage` because cache entries there are less sticky. That said, I'm okay with both options. However before considering changing defaults I'd say we tell users about the option and see if there are any issues.
